name: foxy

on: [push, pull_request]

jobs:
    job1:
        name: Build
        runs-on: ubuntu-20.04
        steps:
            - name: ROS2 Install
              run: |
                  # Ref: https://index.ros.org/doc/ros2/Installation/Foxy/Linux-Install-Debians/
                  sudo locale-gen en_US en_US.UTF-8
                  sudo update-locale LC_ALL=en_US.UTF-8 LANG=en_US.UTF-8
                  export LANG=en_US.UTF-8
                  sudo apt update && sudo apt install curl gnupg2 lsb-release
                  curl -s https://raw.githubusercontent.com/ros/rosdistro/master/ros.asc | sudo apt-key add -
                  sudo sh -c 'echo "deb [arch=amd64,arm64] http://packages.ros.org/ros2/ubuntu `lsb_release -cs` main" > /etc/apt/sources.list.d/ros2-latest.list'
                  sudo apt update
                  sudo apt install ros-foxy-desktop
                  source /opt/ros/foxy/setup.bash
            - name: Create Workspace
              run: |
                  mkdir -p ~/ros2_ws/src
            - name: Install repos and dependencies
              run: |
                  source /opt/ros/foxy/setup.bash
                  sudo apt install -y python3-rosdep2
                  sudo apt-get install python3-vcstool
                  sudo apt-get install xdotool
                  sudo apt-get install libompl-dev ompl-demos
                  rosdep update
                  cd ~/ros2_ws
                  wget https://raw.githubusercontent.com/jediofgever/vox_nav/foxy/underlay.repos
                  vcs import src < underlay.repos     
                  rosdep install -y -r -q --from-paths src --ignore-src --rosdistro foxy   
                  colcon build --symlink-install --cmake-args -DCMAKE_BUILD_TYPE=Release --packages-skip-regex vox_nav
                  sudo cp install/ompl/lib/libompl.so* /usr/local/lib/
                  sudo cp install/casadi/lib/libcasadi.so* /usr/local/lib/
            - name: Build packages
              run: |
                  source /opt/ros/foxy/setup.bash
                  # Install colcon
                  # Ref: https://index.ros.org/doc/ros2/Tutorials/Colcon-Tutorial/
                  sudo apt install python3-colcon-common-extensions
                  cd ~/ros2_ws
                  colcon build --symlink-install --cmake-args -DCMAKE_BUILD_TYPE=Release --packages-skip-regex archived_
                  source ~/ros2_ws/install/setup.bash